name: toolhang
task_type: single_dataset
task_modes: []

shape_meta: &shape_meta
  image_resolution: 240
  action:
    shape:
    - 10
  obs:
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 240
      - 240
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
    sideview_image:
      shape:
      - 3
      - 240
      - 240
      type: rgb
      
dataset:
  _target_: unified_video_action.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  language_emb_model: null
  abs_action: true
  dataset_path: data/tool_hang/ph/image_abs.hdf5
  horizon: 32
  n_obs_steps: null
  pad_after: 7
  pad_before: 1
  rotation_rep: rotation_6d
  seed: 42
  use_cache: true
  val_ratio: 0.02
  data_aug: false
  normalizer_type: all

env_runner:
  _target_: unified_video_action.env_runner.robomimic_image_runner.RobomimicImageRunner
  shape_meta: *shape_meta
  abs_action: true
  crf: 22
  dataset_path: data/tool_hang/ph/image_abs.hdf5
  fps: 10
  max_steps: 700
  n_action_steps: 8
  n_envs: 28
  n_obs_steps: 16
  n_test: 50
  n_test_vis: 4
  n_train: 6
  n_train_vis: 2
  past_action: false
  render_obs_key: sideview_image
  test_start_seed: 100000
  tqdm_interval_sec: 1.0
  train_start_idx: 0
